# Generated by Django 2.1.7 on 2019-03-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='components',
        ),
    ]
