# Generated by Django 2.1.7 on 2019-04-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_remove_component_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
